# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:mac)

platform :mac do
  desc "Build"
  lane :build do
    build_app(
      scheme: "NoisyTyper",
      archive: true,
      archive_path: "./build/NoisyTyper.xcarchive"
      )
    automatic_code_signing(
        path: "NoisyTyper.xcodeproj",
        use_automatic_signing: true
        )
  end
end
